Add topic scripting guide page
brigadecore/docs-portuguese pull request #21
Opened 2022-05-17 11:35 UTC by jorgearteiro

fixes #11

2022-05-18 18:23 UTC, felipeschulz requested changes
Some reviews on translate like plural, pronoums and concordances

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +Esta é a saída da criação de um evento e depois chamamos o comando de visualizalção dos logs do job:
o comando de **visualização** dos logs

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +abilitado, o socket do docker presente no Node do Kubernetes que esta rodando o Pod
Quando **habilitado**, o socket...

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +aonde o container precisa usar o Docker daemon do Host. Esta prática é altamente
**onde**

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +da seção `jobPolicies` da especicação do worker definida como `true`. O padrão é  `false`,
"da **especificação** do"

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +Este exemplo de configuração de projeto abilita este recurso:
**habilita**

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +* Se você deseja mais detalhes sobre a interface Brigadier JS/TS API, dê uma olhada na
"veja a documentação"

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +que o projeto referencia. Nos vemos estes scripts como um tipo de orquestrador de shell scripts,
**Nós** vemos

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
>  - Não estamos utlizando o objeto `event` neste script, mas nos iremos utilizá-lo
mas **nós** iremos

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
>  A primeira coisa para perceber aqui é que _nos alteramos a primeira linha_. Além de
é que **_nós** alteramos a primeira linha_.

2022-05-18 18:23 UTC, felipeschulz commented on conteudo/topicos/scripting/guia.md
> +importar o objeto `events`, nos também estamos importando `Job`. `Job` é a classe
**nós** também

2022-05-19 00:03 UTC, jorgearteiro commented on conteudo/topicos/scripting/guia.md
> +> sucesso/fracasso do job é determinado pelo código de saída do `primaryContainer`
done

2022-05-19 00:10 UTC, jorgearteiro commented on conteudo/topicos/scripting/guia.md
> +testes de integração) e aquelas verificações que requerem menos recrusos para serem processadas como(exemplo: linting, teste unitário). Ambos os grupos podem executar os jobs simultaneamente, mas os
dei uma arrumada, mas esta certo assim mesmo! valeu

2022-05-19 00:52 UTC, felipeschulz approved these changes

2022-05-19 00:52 UTC, merged

2022-05-19 00:52 UTC, felipeschulz commented
LGTM